# Practice Notebook


In [ ]:
print("Hello from Jupyter!")

Usefull Function of String

In [ ]:
name="divyansh Kumar sinGH"
lenght=len(name)
print("Lenght of the name is:", lenght)
print("Name in uppercase:", name.upper())
print("Name in lowercase:", name.lower())
print("Number of spaces in the name:", name.count(" "))
print("Is all alphabet characters in the name:", name.isalpha())
print(f"Full name without space is {name.replace(' ','')}")
print(f"The first occurance of 'i' is at index {name.find('i')}",f"so place is {float(name.find('i'))+1} ")


indexing strings ; Variable[start:end:step]

In [ ]:
creditcard = "1234-4567-8901-2345"
print("cridit card number is", creditcard)
print("last 4 digits of credit card are:",creditcard[-4:])
print(creditcard[0:5])

Email silcer function ; .index function

In [ ]:
email = input("Enter your email:")
index = email.index("@")
print("Your username is :",email[0:index])
print("Your domain name is :",email[-index+1:])

# Find max number (sort descending)

In [ ]:
roll_input = input("enter your roll numbers:")
print("Your roll number is :",roll_input)
digits = [int(char) for char in roll_input if char.isdigit()]
#max_digits = sorted(digits, reverse=True)
#print("The highest number formable from digits is :", "".join(max_digits))
print(digits)

In [ ]:
import numpy as np
x =np.linspace(0, 10, 100)
print(x)

In [ ]:
if n := range(1,6):
    for n in n:
     print(n ,"-", n*n)

In [3]:
import numpy as np
# A 1D array (often called a vector)
vec = np.array([1, 2, 3])

# A 2D array (often called a matrix)
mat = np.array([[1, 2, 3], [4, 5, 6]])
print("1D Array (Vector):", vec, "Shape:", vec.shape,"2D Array (Matrix):", mat, "Shape:", mat.shape)
print(mat)

1D Array (Vector): [1 2 3] Shape: (3,) 2D Array (Matrix): [[1 2 3]
 [4 5 6]] Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [5]:
for i in range(10):
    if i%2==0 :
        print(f"{i} is even")

0 is even
2 is even
4 is even
6 is even
8 is even


In [11]:
def is_even(i):
    return i%2==0

is_even(5)

False