# NumPy Homework Assignment
---
**Name:** Divyansh Kumar Singh  
**Student ID:** 251030041  
**Course:** CE613 
**Date:** January 20, 2026

---

**Note:** Questions 17, 26-28, 48, 54, 74, and 97 were not included in the provided assignment list.

## Question 1
Import the numpy package under the name np.

In [191]:
import numpy as np  
print(np.__name__)

numpy


## Question 2
Print the numpy version and the configuration.

In [192]:
print(np.__version__)
np.show_config()  

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: D:/anaconda/Library/include
    lib directory: D:/anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: D:/anaconda/Library/include
    lib directory: D:/anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu

## Question 3
Create a null vector of size 10.

In [193]:
Z = np.zeros(10) 
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Question 4
How to find the memory size of any array.

In [194]:
Z = np.zeros((5, 5))
print(Z.nbytes) 
print(Z.size * Z.itemsize)  

200
200


## Question 5
How to get the documentation of the numpy add function from the command line?

In [195]:

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

## Question 6
Create a null vector of size 10 but the fifth value which is 1.

In [196]:
Z = np.zeros(10)
Z[4] = 1 
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Question 7
Create a vector with values ranging from 10 to 49.

In [197]:
Z = np.arange(10, 50) 
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Question 8
Reverse a vector (first element becomes last).

In [198]:
Z = np.arange(10, 50)
Z_reversed = Z[::-1] 
print(Z_reversed)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Question 9
Create a 3x3 matrix with values ranging from 0 to 8.

In [285]:
Z = np.arange(9).reshape(3, 3)  # reshape turns 1D into 2D
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Question 10
Find indices of non-zero elements from [1,2,0,0,4,0].

In [200]:
Z = np.array([1, 2, 0, 0, 4, 0])
idx = np.nonzero(Z)  # nonzero returns indices where values are not 0
print(idx)

(array([0, 1, 4]),)


## Question 11
Create a 3x3 identity matrix.

In [201]:
Z = np.eye(3)  # eye creates identity matrix
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Question 12
Create a 3x3x3 array with random values.

In [202]:
Z = np.random.random((3, 3, 3))  # random creates values in [0,1)
print(Z)

[[[0.23232202 0.86756108 0.46964562]
  [0.84810411 0.7768013  0.56729321]
  [0.91856689 0.16093452 0.51177047]]

 [[0.52371543 0.0769903  0.44321492]
  [0.10051887 0.43706451 0.21959388]
  [0.10839121 0.56831605 0.40178401]]

 [[0.14559664 0.47186905 0.72102254]
  [0.36560476 0.43343297 0.90303385]
  [0.99836702 0.54954163 0.55618121]]]


## Question 13
Create a 10x10 array with random values and find the minimum and maximum values.

In [203]:
Z = np.random.random((10, 10))
print(Z.min())  # min finds smallest value
print(Z.max())  # max finds largest value

0.008922214378068283
0.967172248346189


## Question 14
Create a random vector of size 30 and find the mean value.

In [204]:
Z = np.random.random(30)
print(Z.mean())  # mean computes average

0.5318418704290617


## Question 15
Create a 2d array with 1 on the border and 0 inside.

In [205]:
Z = np.ones((5, 5))
Z[1:4, 1:4] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Question 16
How to add a border (filled with 0's) around an existing array?

In [206]:
A = np.ones((3, 3))
Z = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Question 17
*(This question was not in the assignment)*

## Question 18
Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [207]:
Z = np.diag([1, 2, 3, 4], k=-1) 
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Question 19
Create a 8x8 matrix and fill it with a checkerboard pattern.

In [208]:
Z = np.tile([[0, 1], [1, 0]], (4, 4)) 
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Question 20
Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [209]:
idx = np.unravel_index(100, (6, 7, 8)) 
print(idx)

(np.int64(1), np.int64(5), np.int64(4))


## Question 21
Create a checkerboard 8x8 matrix using the tile function.

In [210]:
Z = np.tile([[0, 1], [1, 0]], (4, 4)) 
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Question 22
Normalize a 5x5 random matrix.

In [211]:
Z = np.random.random((5, 5))
Z = (Z - Z.min()) / (Z.max() - Z.min()) 
print(Z)

[[0.36569439 0.38133971 0.66063666 0.32854253 0.63499251]
 [0.14037998 0.07186928 0.1429408  0.53964397 0.25385501]
 [0.79894335 0.20256759 0.         0.40134856 0.25165846]
 [0.22073833 0.22706835 0.29303103 0.16751986 0.5783097 ]
 [0.83740907 1.         0.18544704 0.95570351 0.23145756]]


## Question 23
Create a custom dtype that describes a color as four unsigned bytes (RGBA).

In [212]:
rgba = np.dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])
print(rgba)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


## Question 24
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [213]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
Z = A @ B
print(Z)

[[1.02851392 0.93940691]
 [0.99636276 0.6530184 ]
 [1.20888668 0.84584008]
 [1.57745954 1.14036217]
 [1.23725635 1.11358279]]


## Question 25
Given a 1D array, negate all elements which are between 3 and 8, in place.

In [214]:
Z = np.arange(11)
mask = (Z > 3) & (Z < 8)  
Z[mask] *= -1 
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Question 26
*(This question was not listed in the assignment text)*

## Question 27
*(This question was not listed in the assignment text)*

## Question 28
*(This question was not listed in the assignment text)*

## Question 29
How to round away from zero a float array?

In [215]:
Z = np.array([-1.2, -0.2, 0.2, 1.2])
Z_away = np.where(Z > 0, np.ceil(Z), np.floor(Z))
print(Z_away)

[-2. -1.  1.  2.]


## Question 30
How to find common values between two arrays?

In [216]:
A = np.array([1, 2, 3, 4])
B = np.array([3, 4, 5, 6])
common = np.intersect1d(A, B) 
print(common)

[3 4]


## Question 31
How to ignore all numpy warnings (not recommended)?

In [217]:
old_settings = np.seterr(all='ignore') 

np.seterr(**old_settings)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

## Question 32
Is the following expression true? $\sqrt{-1} == \text{nan}$

In [218]:
expr = np.sqrt(-1) == np.nan
print(expr)  
print(np.isnan(np.sqrt(-1)))

False
True


C:\Users\DKS\AppData\Local\Temp\ipykernel_16876\2559599387.py:1: RuntimeWarning: invalid value encountered in sqrt
  expr = np.sqrt(-1) == np.nan
C:\Users\DKS\AppData\Local\Temp\ipykernel_16876\2559599387.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))


## Question 33
How to get the dates of yesterday, today and tomorrow?

In [219]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(f"yesterday: {yesterday}, today: {today}, tomorrow: {tomorrow}")

yesterday: 2026-01-18, today: 2026-01-19, tomorrow: 2026-01-20


## Question 34
How to get all the dates corresponding to the month of July 2016?

In [220]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(f"dates: {dates}")

dates: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## Question 35
How to compute $((A+B)*(-A/2))$ in place (without copy)?

In [221]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))

np.add(A, B, out=B) 
np.multiply(A, -0.5, out=A) 
np.multiply(B, A, out=A)
print(A)

[[-0.29820716 -0.70130478 -0.34500502]
 [-0.04888202 -0.01921503 -0.65982202]
 [-0.189473   -0.03834481 -0.00296393]]


## Question 36
Extract the integer part of a random array of positive numbers using 4 different methods.

In [222]:
Z = np.random.random(5) * 10
print(np.floor(Z))  
print(np.trunc(Z))  
print(Z.astype(int)) 
print(Z // 1)  

[6. 3. 0. 0. 2.]
[6. 3. 0. 0. 2.]
[6 3 0 0 2]
[6. 3. 0. 0. 2.]


## Question 37
Create a 5x5 matrix with row values ranging from 0 to 4.

In [223]:
Z = np.tile(np.arange(5), (5, 1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## Question 38
Consider a generator function that generates 10 integers and use it to build an array.

In [224]:
def gen():
    for i in range(10):
        yield i

Z = np.fromiter(gen(), dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


## Question 39
Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [225]:
Z = np.linspace(0, 1, 12)[1:-1]  
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## Question 40
Create a random vector of size 10 and sort it.

In [226]:
Z = np.random.random(10)
Z_sorted = np.sort(Z) 
print(Z_sorted)

[0.18716758 0.38860808 0.51229956 0.66270251 0.74125841 0.90849042
 0.9086789  0.91260555 0.93124633 0.94732881]


## Question 41
How to sum a small array faster than np.sum?

In [227]:
Z = np.arange(10)
print(np.add.reduce(Z))

45


## Question 42
Consider two random arrays A and B, check if they are equal.

In [228]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
print(np.array_equal(A, B)) 

False


## Question 43
Make an array immutable (read-only).

In [229]:
Z = np.zeros(5)
Z.flags.writeable = False 
print(Z)

[0. 0. 0. 0. 0.]


## Question 44
Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [230]:
Z = np.random.random((10, 2))
x, y = Z[:, 0], Z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar = np.column_stack((r, theta))
print(polar)

[[0.28344423 1.46587347]
 [0.46591495 0.26970031]
 [0.96343186 1.12372412]
 [1.21324216 0.73039298]
 [0.90806835 1.31097778]
 [0.77859494 1.06520988]
 [0.94229199 1.20670786]
 [0.74715705 0.08528067]
 [0.51216386 0.35896774]
 [0.36960235 0.11115475]]


## Question 45
Create random vector of size 10 and replace the maximum value by 0.

In [231]:
Z = np.random.random(10)
Z[Z.argmax()] = 0 
print(Z)

[0.37912518 0.55018621 0.12995667 0.04750239 0.96903469 0.85335479
 0.83244131 0.         0.89648827 0.93827745]


## Question 46
Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

In [232]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
Z = np.zeros(X.size, dtype=[('x', float), ('y', float)])
Z['x'] = X.ravel()
Z['y'] = Y.ravel()
print(Z[:5])

[(0.  , 0.) (0.25, 0.) (0.5 , 0.) (0.75, 0.) (1.  , 0.)]


## Question 48
*(This question was not listed in the assignment text)*

## Question 49
How to print all the values of an array?

In [234]:
Z = np.arange(100)
for i in Z:
    print(i, end=' ')  

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

## Question 50
How to find the closest value (to a given scalar) in a vector?

In [235]:
Z = np.array([0.1, 0.4, 0.7, 1.0])
v = 0.6
idx = np.abs(Z - v).argmin()
print(Z[idx])

0.7


## Question 51
Create a structured array representing a position (x,y) and a color (r,g,b).

In [236]:
dtype = [('x', float), ('y', float), ('r', 'u1'), ('g', 'u1'), ('b', 'u1')]
Z = np.zeros(3, dtype=dtype)
print(Z)

[(0., 0., 0, 0, 0) (0., 0., 0, 0, 0) (0., 0., 0, 0, 0)]


## Question 52
Consider a random vector with shape (100,2) representing coordinates, find point by point distances.

In [237]:
Z = np.random.random((100, 2))
dist = np.sqrt(((Z[1:] - Z[:-1]) ** 2).sum(axis=1))
print(dist[:5])

[0.18834359 0.90478262 0.23513754 0.45024315 0.87836367]


## Question 53
How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [238]:
Z = (np.random.random(5) * 10).astype(np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z, Z.dtype)

[0 1 7 1 9] int32


## Question 54
*(This question was not listed in the assignment text)*

## Question 55
What is the equivalent of enumerate for numpy arrays?

In [239]:
Z = np.array([[10, 20], [30, 40]])
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


## Question 56
Generate a generic 2D Gaussian-like array.

In [240]:
x = np.linspace(-1, 1, 7)
y = np.linspace(-1, 1, 7)
X, Y = np.meshgrid(x, y)
Z = np.exp(-(X**2 + Y**2))
print(Z)

[[0.13533528 0.23587708 0.32919299 0.36787944 0.32919299 0.23587708
  0.13533528]
 [0.23587708 0.41111229 0.57375342 0.64118039 0.57375342 0.41111229
  0.23587708]
 [0.32919299 0.57375342 0.8007374  0.89483932 0.8007374  0.57375342
  0.32919299]
 [0.36787944 0.64118039 0.89483932 1.         0.89483932 0.64118039
  0.36787944]
 [0.32919299 0.57375342 0.8007374  0.89483932 0.8007374  0.57375342
  0.32919299]
 [0.23587708 0.41111229 0.57375342 0.64118039 0.57375342 0.41111229
  0.23587708]
 [0.13533528 0.23587708 0.32919299 0.36787944 0.32919299 0.23587708
  0.13533528]]


## Question 57
How to randomly place p elements in a 2D array?

In [241]:
m, n, p = 5, 5, 8
Z = np.zeros((m, n), dtype=int)
idx = np.random.choice(m * n, p, replace=False)
Z.flat[idx] = 1 
print(Z)

[[0 0 1 1 0]
 [0 1 0 0 0]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [0 0 1 0 0]]


## Question 58
Subtract the mean of each row of a matrix.

In [242]:
Z = np.random.random((3, 5))
Z = Z - Z.mean(axis=1, keepdims=True)
print(Z)

[[-0.07940763 -0.18488551  0.08352142 -0.26192026  0.44269198]
 [ 0.29998296 -0.26373327 -0.08046565  0.45437422 -0.41015826]
 [ 0.31122369 -0.04402741 -0.38235233  0.00852695  0.10662909]]


## Question 59
How to sort an array by the nth column?

In [243]:
Z = np.random.randint(0, 10, (5, 3))
n = 1 
Z_sorted = Z[Z[:, n].argsort()]
print(Z_sorted)

[[3 4 7]
 [8 6 3]
 [6 6 3]
 [6 7 0]
 [8 9 7]]


## Question 60
How to tell if a given 2D array has null columns?

In [244]:
Z = np.array([[0, 1, 0], [0, 2, 0], [0, 3, 0]])
null_cols = np.all(Z == 0, axis=0) 
print(null_cols)

[ True False  True]


## Question 61
Find the nearest value from a given value in an array.

In [245]:
Z = np.array([0.2, 0.5, 0.9])
v = 0.6
nearest = Z[np.abs(Z - v).argmin()]
print(nearest)

0.5


## Question 64
Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [248]:
Z = np.zeros(5)
idx = np.array([1, 1, 3])
np.add.at(Z, idx, 1)
print(Z)

[0. 2. 0. 1. 0.]


## Question 65
How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [249]:
X = np.array([1, 2, 3, 4])
I = np.array([0, 1, 1, 3])
F = np.zeros(4)
np.add.at(F, I, X)
print(F)

[1. 5. 0. 4.]


## Question 66
Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors.

In [250]:
image = np.random.randint(0, 256, (4, 4, 3), dtype=np.uint8)
colors = np.unique(image.reshape(-1, 3), axis=0)
print(len(colors))

16


## Question 67
Considering a four dimensions array, how to get sum over the last two axis at once?

In [251]:
Z = np.random.random((2, 3, 4, 5))
S = Z.sum(axis=(-2, -1))
print(S.shape)

(2, 3)


## Question 70
Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [254]:
Z = np.array([1, 2, 3, 4, 5])
out = np.zeros(len(Z) * 4 - 3, dtype=int)
out[::4] = Z
print(out)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


## Question 71
Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

In [255]:
Z = np.random.random((5, 5, 3))
M = np.random.random((5, 5))
out = Z * M[:, :, None]
print(out.shape)

(5, 5, 3)


## Question 72
How to swap two rows of an array?

In [256]:
Z = np.arange(9).reshape(3, 3)
Z[[0, 2]] = Z[[2, 0]]
print(Z)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## Question 73
Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles.

In [257]:
triangles = np.random.randint(0, 20, (10, 3))
edges = np.vstack([triangles[:, [0, 1]], triangles[:, [1, 2]], triangles[:, [2, 0]]])
unique_edges = np.unique(edges, axis=0)
print(unique_edges)

[[ 0  9]
 [ 1  4]
 [ 1 13]
 [ 1 14]
 [ 2  6]
 [ 2 10]
 [ 2 16]
 [ 3  2]
 [ 3  3]
 [ 3 11]
 [ 4 10]
 [ 5  2]
 [ 6  3]
 [ 6  8]
 [ 8  6]
 [ 8  8]
 [ 9  0]
 [ 9  9]
 [ 9 10]
 [10  0]
 [10  1]
 [10  5]
 [11  1]
 [11  3]
 [13  2]
 [13 11]
 [14  1]
 [14 14]
 [16 13]]


## Question 74
*(This question was not listed in the assignment text)*

## Question 75
How to compute averages using a sliding window over an array?

In [258]:
Z = np.arange(10, dtype=float)
k = 3
avg = np.convolve(Z, np.ones(k) / k, mode='valid')
print(avg)

[1. 2. 3. 4. 5. 6. 7. 8.]


## Question 77
How to negate a boolean, or to change the sign of a float inplace?

In [260]:
Z_bool = np.array([True, False, True])
Z_bool = np.logical_not(Z_bool) 
Z_float = np.array([1.0, -2.0, 3.0])
Z_float *= -1
print(Z_bool)
print(Z_float)

[False  True False]
[-1.  2. -3.]


## Question 78
Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [261]:
P0 = np.random.random((5, 2))
P1 = np.random.random((5, 2))
p = np.array([0.5, 0.5])
v = P1 - P0
w = p - P0
dist = np.abs(np.cross(v, w)) / np.linalg.norm(v, axis=1)
print(dist)

[0.23758597 0.48897321 0.06391628 0.15344566 0.24004416]


C:\Users\DKS\AppData\Local\Temp\ipykernel_16876\4263952395.py:6: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  dist = np.abs(np.cross(v, w)) / np.linalg.norm(v, axis=1)


## Question 79
Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [262]:
P0 = np.random.random((3, 2))
P1 = np.random.random((3, 2))
P = np.random.random((4, 2))
v = P1 - P0  
w = P[:, None, :] - P0[None, :, :]  
cross = np.abs(v[None, :, 0] * w[:, :, 1] - v[None, :, 1] * w[:, :, 0])
dist = cross / np.linalg.norm(v, axis=1)[None, :]
print(dist)

[[0.31274492 0.27567337 0.25210037]
 [0.47739479 0.34574317 0.42555577]
 [0.27770246 0.18277565 0.17013338]
 [0.51525192 0.46185528 0.52662248]]


## Question 80
Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary).

In [263]:
def extract_subpart(Z, center, shape, fill=0):
    pad_y = shape[0] // 2
    pad_x = shape[1] // 2
    Zp = np.pad(Z, ((pad_y, pad_y), (pad_x, pad_x)), mode='constant', constant_values=fill)
    y, x = center
    y += pad_y
    x += pad_x
    return Zp[y - pad_y:y + pad_y + 1, x - pad_x:x + pad_x + 1]

Z = np.arange(25).reshape(5, 5)
print(extract_subpart(Z, center=(0, 0), shape=(3, 3), fill=-1))

[[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


## Question 82
Compute a matrix rank.

In [265]:
Z = np.random.random((4, 4))
rank = np.linalg.matrix_rank(Z)
print(rank)

4


## Question 83
How to find the most frequent value in an array?

In [266]:
Z = np.array([1, 2, 2, 3, 3, 3, 4])
values, counts = np.unique(Z, return_counts=True)
most_frequent = values[counts.argmax()] 
print(most_frequent)

3


## Question 87
Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [270]:
Z = np.random.random((16, 16))
block_sum = Z.reshape(4, 4, 4, 4).sum(axis=(1, 3))
print(block_sum.shape)  # (4,4)

(4, 4)


## Question 88
How to implement the Game of Life using numpy arrays?

In [271]:

Z = np.random.randint(0, 2, (5, 5))

# Count live neighbors using wrap-around boundaries
neighbors = (
    np.roll(Z, 1, axis=0) + np.roll(Z, -1, axis=0) +
    np.roll(Z, 1, axis=1) + np.roll(Z, -1, axis=1) +
    np.roll(np.roll(Z, 1, axis=0), 1, axis=1) +
    np.roll(np.roll(Z, 1, axis=0), -1, axis=1) +
    np.roll(np.roll(Z, -1, axis=0), 1, axis=1) +
    np.roll(np.roll(Z, -1, axis=0), -1, axis=1)
)

# Apply Game of Life rules
Z_next = ((neighbors == 3) | ((Z == 1) & (neighbors == 2))).astype(int)

print("Initial Grid:")
print(Z)

print("\nNext Generation:")
print(Z_next)


Initial Grid:
[[0 1 1 1 1]
 [0 0 1 1 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [1 0 1 1 0]]

Next Generation:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]]


## Question 89
How to get the n largest values of an array?

In [272]:
Z = np.random.random(10)
n = 3
largest = np.partition(Z, -n)[-n:]
print(largest)

[0.40948902 0.73861261 0.90222753]


## Question 91
How to create a record array from a regular array?

In [ ]:
Z = np.array([[1, 2], [3, 4]])

rec = np.rec.fromarrays(Z.T, names='x,y')
print(rec)

[(1, 2) (3, 4)]


## Question 92
Consider a large vector Z, compute Z to the power of 3 using 3 different methods.

In [275]:
Z = np.random.random(5)
print(Z ** 3)  
print(np.power(Z, 3)) 
print(Z * Z * Z)

[0.24008239 0.00662881 0.04734074 0.24148709 0.12634483]
[0.24008239 0.00662881 0.04734074 0.24148709 0.12634483]
[0.24008239 0.00662881 0.04734074 0.24148709 0.12634483]


## Question 93
Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [ ]:
A = np.array([[1, 2, 3], [3, 2, 1], [4, 5, 6], [2, 1, 3]])
B = np.array([[1, 2], [4, 6]])

selected_rows = []
for row in A:
    for target in B:
        if np.all(np.isin(target, row)):
            selected_rows.append(row)
            break

print(np.array(selected_rows))

[[1 2 3]
 [3 2 1]
 [4 5 6]
 [2 1 3]]


## Question 94
Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]).

In [277]:
Z = np.array([[2, 2, 2], [2, 2, 3], [1, 1, 1], [3, 4, 5]])
mask = np.any(np.diff(Z, axis=1), axis=1)  
print(Z[mask])

[[2 2 3]
 [3 4 5]]


## Question 95
Convert a vector of ints into a matrix binary representation.

In [278]:
Z = np.array([1, 2, 3, 4], dtype=np.uint8)
B = np.unpackbits(Z[:, None], axis=1) 
print(B)

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]]


## Question 96
Given a two dimensional array, how to extract unique rows?

In [279]:
Z = np.array([[1, 2], [1, 2], [3, 4]])
unique_rows = np.unique(Z, axis=0)
print(unique_rows)

[[1 2]
 [3 4]]


## Question 98
Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

In [280]:
X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 1, 2, 2])
dx = np.diff(X)
dy = np.diff(Y)
dist = np.sqrt(dx**2 + dy**2)
t = np.concatenate([[0], np.cumsum(dist)])
t_new = np.linspace(0, t[-1], 10)
X_new = np.interp(t_new, t, X)
Y_new = np.interp(t_new, t, Y)
print(np.column_stack((X_new, Y_new)))

[[0.         0.        ]
 [0.37935706 0.37935706]
 [0.75871412 0.75871412]
 [1.19526215 1.        ]
 [1.73175405 1.        ]
 [2.18967853 1.18967853]
 [2.56903559 1.56903559]
 [2.94839266 1.94839266]
 [3.4635081  2.        ]
 [4.         2.        ]]


## Question 99
Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees.

In [281]:
n = 4
X = np.array([[1, 1, 2], [2, 2, 1], [1.5, 1, 1.5], [0, 4, 0]])
is_int = np.all(X == X.astype(int), axis=1)
row_sum = X.sum(axis=1) == n
mask = is_int & row_sum
print(X[mask])

[[1. 1. 2.]
 [0. 4. 0.]]


## Question 100
Compute bootstrapped 95% confidence intervals for the mean of a 1D array X.

In [282]:
X = np.random.random(100)
N = 1000 
idx = np.random.randint(0, len(X), (N, len(X)))
means = X[idx].mean(axis=1)
ci = np.percentile(means, [2.5, 97.5])  
print(ci)

[0.41653372 0.53465165]
